---

- name: Install personal computer specific software
  package: name={{ item }} state=latest
  ignore_errors: true
  with_items:
    - texmaker
    - thunderbird
    - vlc
    - gimp
    - nmap
    - pgadmin3
    - youtube-dl
    - deluge
    - gnupg
    - gparted
    - hexchat
    - unetbootin


