---
- hosts: dads_laptop
  become: true
  roles: 
    - common

# - hosts: personal_use
#   become: true
#   roles:
#     - personal

# - hosts: webserver
#   become: true
#   roles:
#     - webserver

