---

- name: Copy across iptables.rules
  template: 
    src: "{{ role_path }}/templates/iptables.rules"
    dest: /etc/iptables/iptables.rules 
    owner: root
    mode: "u=rw,og=r"
  notify: 
    - reload iptables

