---

- name: Install audit
  package:
    name: auditd
    state: latest

- name: Create /etc/audit
  file:
    dest: /etc/audit
    owner: root
    state: directory

- name: Create /etc/audit/rules.d
  file:
    dest: /etc/audit/rules.d
    owner: root
    state: directory

- name: Watch all files with setuid/gid bit
  script:  "{{ role_path }}/files/find_setuid.sh"
  become_user: root
  register: set_uid

- debug: msg="Added {{ set_uid.stdout_lines|length }} rules"

- name: Copy across 1_preamble.rules
  copy:
    src: "{{ role_path }}/files/1_preamble.rules"
    dest: /etc/audit/rules.d/1_preamble.rules
    owner: root
    group: root

- name: Delete everything else in the rules folder
  file:
    dest: /etc/audit/rules.d/audit.rules
    state: absent

- name: Merge all rules into one file
  assemble:
    src: /etc/audit/rules.d
    dest: /etc/audit/audit.rules
    owner: root
    group: root

- name: Restart auditd
  service:
    name: auditd
    state: restarted
    enabled: true

- name: Copy across reporting script
  copy:
    src: "{{ role_path }}/files/audit_reporting.sh"
    dest: /etc/audit/audit_reporting.sh
    owner: root
    group: root
    mode: "u=rwx"

# audit reports
# =============

- name: Create report emailing crontab
  cron:
    name: emailed auditing report
    job: sudo /etc/audit/audit_reporting.sh | email -s "[monitoring] {{ ansible_hostname }}" michaelfbryan@gmail.com
    state: present
    day: "*"
    hour: 0
    minute: 0
    user: "{{ ansuble_user }}"

- name: Create reports folder
  file:
    dest: /root/reports
    state: directory
    owner: root

- name: Create local report crontab
  cron:
    name: local auditing report
    job: sudo sh -c '/etc/audit/audit_reporting.sh > /root/reports/report_$(date "+%F").txt'
    state: present
    day: "*"
    hour: 0
    minute: 0
    user: "{{ ansible_user }}"


# LogWatch
# ========

# Configure it for all ubuntu boxes

- name: Install Postfix
  package: name=postfix state=latest
  when: ansible_distribution == 'Ubuntu'

- name: Transfer across /etc/aliases
  copy:
    src: "{{ role_path }}/files/aliases"
    dest: /etc/aliases
    owner: root
    group: root
    mode: "u=rw,og=r"

- name: Set up Postfix to relay mail
  debconf: 
    name: postfix
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { question: "postfix/mailname", value: "{{ ansible_fqdn }}", vtype: "string" }
    - { question: "postfix/main_mailer_type", value: "Internet Site", vtype: "string" }
  when: ansible_distribution == 'Ubuntu'

- name: Install LogWatch
  package: name=logwatch state=latest
  when: ansible_distribution == 'Ubuntu'

- name: Create LogWatch daily reports
  cron:
    name: logwatch daily report
    job: sudo /usr/sbin/logwatch --detail high | email -s "[monitoring] {{ ansible_hostname }}" michaelfbryan@gmail.com 
    state: present
    day: "*"
    hour: 0
    minute: 0
    user: "{{ ansible_user }}"
  when: ansible_distribution == 'Ubuntu'

