---

- name: Install base packages
  package: name={{ item }} state=latest 
  with_items:
    - cmake
    - git
    - gparted
    - hexchat
    - htop
    - iptables
    - nmap
    - ruby
    - tmux
    - tree
    - vlc
    - wget
    - youtube-dl
    - zsh

- name: Ensure UFW isn't installed
  package: name=ufw state=absent

- name: Install Arch specific packages
  package: name={{ item }} state=latest
  when: ansible_distribution == 'Archlinux'
  with_items:
    - cargo
    - cronie
    - gvim
    - keepassx2
    - python-pip
    - rust

- name: Install Ubuntu specific packages
  package: name={{ item }} state=latest
  when: ansible_distribution == 'Ubuntu'
  with_items:
    - cron
    - keepassx
    - python-dev
    - python3-dev
    - python3-matplotlib
    - python3-pip
    - vim-gtk

- name: Install Python packages
  pip: name={{ item }} state=present executable="pip3"
  ignore_errors: true
  with_items:
    - bs4
    - cython
    - flask
    - jupyter
    - matplotlib
    - numpy
    - pandas
    - pyYAML
    - requests
    - sphinx
    - sphinx_rtd_theme
    - sqlalchemy
    - tqdm
    - virtualenv
    - virtualenvwrapper
    - youtube-dl

- name: Check if YouCompleteMe is installed
  stat: path=/usr/local/bin/email
  register: ycm_core_file

