---

- name: Install Ruby
  package: 
    name: ruby
    state: latest

- name: Install pygments
  pip: name=pygments state=latest executable=pip3

- name: Install jekyll dependencies
  gem: name={{ item }} state=latest user_install=false
  with_items:
    - jekyll
    - jekyll-paginate
    - pygments.rb
    - rake

