---

- name: Install Ruby
  package: 
    name: ruby
    state: latest

- name: Install jekyll dependencies
  gem: name={{ item }} state=latest 
  with_items:
    - jekyll
    - jekyll-paginate
    - pygments.rb
    - rake
  become_user: jekyll
  ignore_errors: true

